version: 2
updates:
  # Maintain dependencies for Node.js backend
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Maintain Dockerfiles
  - package-ecosystem: "docker"
    directory: "/docker/web"
    schedule:
      interval: "weekly"

  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
